name: Build MangoBot
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'settings.gradle'

permissions:
  contents: read

jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@main
    with:
      java: 22
      gradle_tasks: "check runDatagen publish"
      artifact_name: "MangoBot"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MAVEN_USER: ${{ secrets.USERNAME }}  # Reference the secret
      MAVEN_PASSWORD: ${{ secrets.PASSWORD }}  # Reference the secret