name: Bump Patch, Publish and Restart Discord Bot (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish: # Publish to maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew

      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.USERNAME }}  # Reference the secret\
          MAVEN_PASSWORD: ${{ secrets.PASSWORD }}  # Reference the secret\
        run: ./gradlew publishMangobotPublicationToMavenRepository -DskipTests

  restart: # Restart Bot
    runs-on: ubuntu-latest
    needs: Publish
    steps:
      - uses: actions/checkout@v3

      - name: Install Java and Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew

      - name: Restart
        env:
          SERVER_ID: ${{ secrets.SERVER_ID }}  # Reference the secret\
          SERVER_TOKEN: ${{ secrets.SERVER_TOKEN }}  # Reference the secret\
        run: ./gradlew restartServer