name: Bump Patch, Publish and Restart Discord Bot (Gradle)

on:
  push:
    branches: [ master ]

jobs:
  publish: # Publish to maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Fix gradlew permissions (optional)
        run: chmod +x gradlew

      - name: Publish
        env:
          MAVEN_USERNAME: ${{ secrets.USERNAME }}  # Reference the secret\
          MAVEN_PASSWORD: ${{ secrets.PASSWORD }}  # Reference the secret\
        run: ./gradlew publishMangobotPublicationToMavenRepository -DskipTests