name: Regen Files
on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: ./.github/workflows/gradle.yml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Regen
        env:
          WH_TOKEN: ${{ secrets.WH_TOKEN }}
        run: |
          curl --header "Authorization: Basic $WH_TOKEN" --header "Content-Type: application/json" --request POST --data "{\"group\": \"org.mangorage\", \"artifact\": \"mangobot\"}" https://webhooks.minecraftforge.net/hooks/regen
